version: "3"
services:
    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ./app:/var/www/app:cached
            - laravel-vendor-volume-bnr-api-service:/var/www/vendor
            - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx

    php:
        restart: always
        image: brian978/php-fpm:8.1-dev
        working_dir: /var/www/app
        depends_on:
            - db
            - cache
        volumes:
            - ./app:/var/www/app:cached
            - laravel-vendor-volume-bnr-api-service:/var/www/vendor
            - ./services/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./services/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./services/bash/.bashrc:/root/.bashrc
            - ./logs/php:/var/log/php
        environment:
            - PHP_IDE_CONFIG=serverName=docker

    db:
        restart: always
        image: mariadb:10.5.8
        ports:
            - "33061:3306"
        volumes:
            - mysql-volume-bnr-api-service:/var/lib/mysql
            - ./services/mysql/conf.d/logging.cnf:/etc/mysql/conf.d/logging.cnf
        environment:
            MYSQL_DATABASE: bnr
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 12345

    cache:
        restart: always
        image: redis:latest

volumes:
    mysql-volume-bnr-api-service:
    laravel-vendor-volume-bnr-api-service:
